spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

  application:
    name: Solactive Social Portal

  thymeleaf:
    cache : false
    enabled : true
    prefix : classpath:/templates
    suffix : .html

